# See https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions
# @author @VKCOM/VKUI-core
name: 'Deprecate NPM package'

on:
  workflow_call:
    inputs:
      package:
        type: 'string'
        description: 'package`s name'
        required: true
      version:
        type: 'string'
        description: 'type version: x.y.z (without "v")'
        required: true
      reason:
        type: 'string'
        description: 'reason for deprecation (only latin supported)'
        required: true
    secrets:
      npm_auth_token:
        description: 'npm auth token'
        required: true

run-name: Deprecate ${{ inputs.package }}@${{ inputs.version }}

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Deprecate version
        run: npm deprecate "${{ inputs.package }}@${{ inputs.version }}" "${{ inputs.reason }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
